"""Authoritative content tables for the ARAPI client guide."""

VERSION = "1.0.0"
REVIEW_DATE = "26 August 2026"

TOC = [
    ("about", "1. About ARAPI"),
    ("release_notes", "2. Read this before using the current release"),
    ("install", "3. Installation and first launch"),
    ("quick_start", "4. End-to-end quick start"),
    ("interface", "5. Interface fundamentals"),
    ("screens", "6. Screen-by-screen guide"),
    ("commands", "7. BotJob command reference"),
    ("variables_env", "8. Variables and environments"),
    ("bash", "9. Bash/curl script generation and execution"),
    ("results", "10. Execution results, history, and reports"),
    ("ai", "11. Bot Builder and AI providers"),
    ("security", "12. Security and operational practices"),
    ("troubleshooting", "13. Troubleshooting"),
    ("status", "14. Feature status matrix"),
    ("controls", "Appendix A. Complete control index"),
    ("api", "Appendix B. Local API reference"),
    ("glossary", "Appendix C. Glossary"),
    ("handoff", "Appendix D. Client acceptance checklist"),
]

NAV_ITEMS = [
    ("Home", "Overview, engine status, and shortcuts to every ARAPI area."),
    ("Import APIs", "Load OpenAPI or Swagger documents from files or a folder."),
    ("API Catalog", "Search the imported method/path inventory and mapping state."),
    ("Business Categories", "Browse the 25-domain banking taxonomy."),
    ("Test Cases", "Reserved reusable-test workspace; creation is disabled in this release."),
    ("Bot Builder", "Use conversational actions to search, create BotJobs, and request runs."),
    ("BotJob Designer", "Create, configure, enable/disable, and order commands."),
    ("Environments", "Manage named base URLs and default headers."),
    ("Scripts", "Generate a BotJob-specific Bash file containing ordered curl calls."),
    ("Execute Tests", "Select a BotJob/environment and review the local run audit."),
    ("Mock Server", "Control the in-app mock state and inspect its request/system log."),
    ("Reports", "Download run reports and whole-catalog exports."),
    ("Settings", "Configure AI provider records and view local-service ports."),
]

CATEGORIES = [
    ("Customer & Onboarding", "New Customer; KYC / Identity; Customer 360; Consents; Offboarding"),
    ("Accounts", "Current Accounts; Savings; Account Details; Statements; Account Closure"),
    ("Balances", "Available Balance; Booked Balance; Holds; Overdraft; Currency Balance"),
    ("Payments & Transfers", "Single Payment; Bulk Payment; Standing Orders; Direct Debit; Cross-Border"),
    ("Cards", "Card Issuance; Card Controls; Transactions; Disputes; Replacement"),
    ("Securities & Trading", "Order Entry; Order Status; Executions; Instruments; Market Data"),
    ("Portfolio & Holdings", "Positions; Allocation; Performance; Valuation; Rebalancing"),
    ("Investment Advisory", "Suitability; Recommendations; Model Portfolios; Risk Profile; Proposals"),
    ("Credit & Lending", "Applications; Limits; Repayments; Collateral; Restructuring"),
    ("Deposits & Treasury", "Term Deposits; Notice Accounts; Treasury Positions; Liquidity; Rates"),
    ("Foreign Exchange", "Spot; Forward; Rates; Conversions; Hedging"),
    ("Compliance & AML", "Screening; Alerts; Case Management; Reporting; Watchlists"),
    ("Risk Management", "Credit Risk; Market Risk; Limits; Exposure; Stress Tests"),
    ("Fraud & Disputes", "Fraud Alerts; Investigations; Chargebacks; Recovery; Reporting"),
    ("Statements & Documents", "Statements; Tax Documents; Contracts; Notices; Archive"),
    ("Notifications & Messaging", "Secure Messages; Push Alerts; Email; SMS; Preferences"),
    ("Authentication & Access", "Sessions; MFA; Consents; Scopes; Devices"),
    ("Beneficiaries & Payees", "Add Payee; Verify Payee; Payee List; Trusted Payees; Removal"),
    ("Standing Orders & Schedules", "Create; Amend; Cancel; Calendar; History"),
    ("Reporting & Analytics", "Operational; Regulatory; Custom; Exports; Coverage"),
    ("Back Office & Settlement", "Settlement; Reconciliation; Corporate Actions; Fees; Adjustments"),
    ("Wealth & Private Banking", "Mandates; Discretionary; Reporting; Fees; Relationship"),
    ("Insurance & Bancassurance", "Policies; Quotes; Premiums; Claims; Renewals"),
    ("Fees & Pricing", "Tariffs; Charges; Refunds; Bundles; Quotes"),
    ("Audit & Operations", "Audit Trail; Event Log; UAT; Health; Maintenance"),
]

COMMANDS = [
    {
        "group": "API", "name": "API_CALL", "label": "API Call", "status": "Configurable",
        "purpose": "Select one real endpoint from the imported catalog and prepare an HTTP request.",
        "configuration": "Endpoint; optional JSON body; optional JSON header object. Body and header values accept ${variable} tokens.",
        "current": "Included by BotJob Bash export when enabled. In the run audit, request/response details are available when the runtime records them.",
    },
    {
        "group": "Variables", "name": "SET_VARIABLE", "label": "Set Variable", "status": "Configurable",
        "purpose": "Create or replace a runtime value for later commands.",
        "configuration": "Variable name and value. The value may contain ${variable} tokens.",
        "current": "Not written as a separate Bash statement by the BotJob exporter; declared BotJob variables drive Bash defaults and guards.",
    },
    {
        "group": "Variables", "name": "EXTRACT_JSON_PATH", "label": "Extract JSON Path", "status": "Configurable",
        "purpose": "Read a value from the most recent JSON response and store it in a variable.",
        "configuration": "JSON path such as $.data.token and destination variable name.",
        "current": "Available in the Designer/runtime model; not converted to Bash by the current exporter.",
    },
    {
        "group": "Assertions", "name": "ASSERT_STATUS_CODE", "label": "Assert Status Code", "status": "Configurable",
        "purpose": "Compare the last response status with an expected HTTP code.",
        "configuration": "Expected integer from 100 through 599, commonly 200 or 201.",
        "current": "Appears in the local run audit; not converted to Bash by the current exporter.",
    },
    {
        "group": "Assertions", "name": "ASSERT_FIELD_VALUE", "label": "Assert Field Value", "status": "Configurable",
        "purpose": "Compare a JSON-path value in the last response with an expected JSON value.",
        "configuration": "JSON path and expected value. Valid JSON input is parsed; otherwise it is treated as text.",
        "current": "Appears in the local run audit; not converted to Bash by the current exporter.",
    },
    {
        "group": "Assertions", "name": "ASSERT_JSON_PATH_EXISTS", "label": "Assert JSON Path Exists", "status": "Configurable",
        "purpose": "Confirm that the requested JSON path exists in the last response.",
        "configuration": "JSON path such as $.data.id.",
        "current": "Appears in the local run audit; not converted to Bash by the current exporter.",
    },
    {
        "group": "Control", "name": "WAIT", "label": "Wait", "status": "Configurable",
        "purpose": "Pause the workflow for a bounded delay.",
        "configuration": "Milliseconds from 0 through 10,000.",
        "current": "Recognized by the execution-engine model; not converted to Bash by the current exporter.",
    },
    {
        "group": "Control", "name": "STOP_ON_FAILURE", "label": "Stop on Failure", "status": "Verify in deployment",
        "purpose": "Mark the workflow to stop after a failure.",
        "configuration": "No visible fields.",
        "current": "The Bash exporter continues remaining curl calls, counts failures, and exits 1 at the end. Acceptance-test desktop stop behavior before relying on it.",
    },
    {
        "group": "Control", "name": "IF", "label": "IF", "status": "Preview",
        "purpose": "Reserved conditional branch start.",
        "configuration": "No configuration editor in this release.",
        "current": "Designer warns that this command is not executed and is recorded as skipped.",
    },
    {
        "group": "Control", "name": "ELSE", "label": "ELSE", "status": "Preview",
        "purpose": "Reserved alternate branch.",
        "configuration": "No configuration editor in this release.",
        "current": "Not executed; recorded as skipped.",
    },
    {
        "group": "Control", "name": "LOOP", "label": "Loop", "status": "Preview",
        "purpose": "Reserved repeated execution block.",
        "configuration": "No configuration editor in this release.",
        "current": "Not executed; recorded as skipped.",
    },
    {
        "group": "Control", "name": "FOR_EACH", "label": "For Each", "status": "Preview",
        "purpose": "Reserved iteration over a collection.",
        "configuration": "No configuration editor in this release.",
        "current": "Not executed; recorded as skipped.",
    },
    {
        "group": "Data", "name": "READ_CSV", "label": "Read CSV", "status": "Preview",
        "purpose": "Reserved CSV-driven data input.",
        "configuration": "No configuration editor in this release.",
        "current": "Not executed; recorded as skipped.",
    },
    {
        "group": "Data", "name": "READ_EXCEL", "label": "Read Excel", "status": "Preview",
        "purpose": "Reserved spreadsheet-driven data input.",
        "configuration": "No configuration editor in this release.",
        "current": "Not executed; recorded as skipped.",
    },
    {
        "group": "Data", "name": "AI_GENERATE_DATA", "label": "AI Generate Data", "status": "Preview",
        "purpose": "Reserved AI-assisted test-data creation.",
        "configuration": "No configuration editor in this release.",
        "current": "Not executed; recorded as skipped.",
    },
    {
        "group": "Data", "name": "CALL_COMPONENT", "label": "Call Component", "status": "Preview",
        "purpose": "Reserved call to a reusable component/test flow.",
        "configuration": "No configuration editor in this release.",
        "current": "Not executed; recorded as skipped. The Test Cases page is also reserved in this release.",
    },
]

SCREENS = [
    ("01-home.png", "Home overview", "The ARAPI Home page showing the online engine indicator, navigation sidebar, Employee/Client selector, and shortcut cards.", "Home provides engine health and shortcuts. Use any card or the matching sidebar item to open a workspace."),
    ("02-import-apis.png", "Import APIs - Folder (Desktop)", "The Import APIs page with the Folder Desktop tab, path field, Browse button, and disabled Import button.", "Choose Browse, select a specification folder, confirm the path, and select Import. Subfolders are scanned."),
    ("14-import-upload.png", "Import APIs - Upload Files", "The Upload Files tab with drag-and-drop area, Browse Files, Browse Folder, and Import controls.", "Drop YAML/JSON files or a folder, or use the browse buttons. Remove unwanted items before selecting Import."),
    ("03-api-catalog.png", "API Catalog", "The API Catalog showing method, path, summary, mapping status, and the search field.", "Search by HTTP method, path, or summary. Mapped/unmapped indicates whether taxonomy mapping exists."),
    ("04-business-categories.png", "Business Categories", "The Business Categories page showing banking-domain cards and their subcategories.", "This is a read-only business view of the 25-domain taxonomy in the current UI."),
    ("05-test-cases.png", "Test Cases", "The Test Cases page with the disabled New test case button and explanatory placeholder.", "The page documents the intended reusable-test concept, but New test case is disabled in version 1.0.0."),
    ("06-bot-builder.png", "Bot Builder - start", "The Bot Builder start screen with prompt suggestions, provider badge, message box, and Send button.", "Select a suggestion or write an instruction. Enter sends; Shift+Enter inserts a new line."),
    ("24-bot-builder-action.png", "Bot Builder - catalog action", "A Bot Builder conversation showing catalog search evidence and an expandable action card.", "Review the returned endpoints and expand action cards. Never assume a conversational result is a production endpoint without catalog evidence."),
    ("07-botjob-designer.png", "BotJob Designer - no selection", "The Designer showing saved BotJobs, an empty canvas, the command palette, and New BotJob.", "Select a saved BotJob or create one. Palette controls stay disabled until a job is selected."),
    ("15-botjob-designer-selected.png", "BotJob Designer - selected job", "A selected BotJob showing name, description, variables, flow commands, Save/Delete, and the command palette.", "Edit metadata and variables, add palette commands, drag the grip to reorder, enable/disable commands, and Save."),
    ("26-designer-command-config.png", "BotJob Designer - API Call configuration", "An expanded API Call command showing endpoint, JSON body, JSON headers, enabled checkbox, collapse, and delete controls.", "Choose an imported endpoint, supply valid optional JSON, and reference variables with ${name}."),
    ("08-environments.png", "Environments", "The Environments page showing the built-in default Mock Server environment and New Environment.", "The built-in record cannot be edited or deleted. Create separate named targets for approved dev, test, or production systems."),
    ("16-environment-form.png", "Environment form", "The new environment form with name, base URL, description, default headers, default checkbox, Cancel, and Save.", "Use one Key: Value header per line. Save is enabled only after Name and Base URL are present."),
    ("09-scripts.png", "Scripts - initial", "The Scripts page with BotJob, Environment, save directory, Browse, and disabled Create Bash Script.", "The action remains disabled until the required selections and desktop output directory are set."),
    ("17-scripts-selected.png", "Scripts - selected BotJob", "The Scripts page with a BotJob and environment selected, base URL shown, and save-directory prompt.", "Choose Browse and use a dedicated directory such as Documents\\ARAPI\\Scripts. Then create the file."),
    ("10-execute-tests.png", "Execute Tests - initial", "The Execute Tests page before a BotJob is selected, with History, environment selector, and disabled Run.", "Select the execution environment and BotJob. Run and Create Scripts appear/enabled only when applicable."),
    ("18-execute-selected.png", "Execute Tests - ready", "Execute Tests with a BotJob selected and the conditional Create Scripts button visible.", "Create Scripts opens the Scripts page with the current BotJob and environment preselected; Run starts the local audit."),
    ("19-execute-results.png", "Execute Tests - result summary", "A completed execution showing status, target, step totals, duration, run ID, and step rows.", "Expand any row for details. Always correlate real-environment results with target-side evidence."),
    ("23-execution-step-detail.png", "Execution step detail", "An expanded API_CALL result row showing Request and Response disclosure controls.", "Expand Request or Response when present. Do not copy sensitive payloads into tickets or client documents."),
    ("20-execution-history.png", "Execution History", "The history panel showing an All BotJobs filter and saved run rows.", "Filter by BotJob and select a run to reload its summary and step results."),
    ("11-mock-server.png", "Mock Server - stopped", "The stopped Mock Server page with Start, port, status, and empty request log.", "Start changes the ARAPI mock state and activates the dashboard log for the current build."),
    ("21-mock-running-log.png", "Mock Server - running", "The running Mock Server dashboard with Stop, statistics, and a system log entry.", "Stop changes state; Clear removes log rows. See the current-build note before treating port 8855 as an external listener."),
    ("12-reports.png", "Reports and Exports", "Reports showing the run selector, HTML and CSV downloads, Postman Collection, and Bash curl catalog export.", "Run exports depend on a selected execution. Catalog exports are independent and cover the whole catalog."),
    ("13-settings.png", "Settings - provider list", "Settings showing supported AI providers, key/default badges, Test, and expand controls.", "A green DEFAULT badge identifies the provider used by AI features. NO KEY providers cannot be selected as default."),
    ("22-settings-provider-form.png", "Settings - provider form", "An expanded OpenAI provider form showing model, masked API-key field, and Save without exposing a key.", "Enter the model and required provider values, save, then use Test as a configuration indicator."),
    ("25-settings-local-services.png", "Settings - local services", "The lower Settings page showing all providers and local sidecar/mock port values.", "These ports are localhost services. Environment-variable overrides are administrator/deployment settings."),
]

CONTROL_INDEX = [
    ("Global", "Employee / Client", "Always", "Changes the shared conversation-mode context; it does not rewrite catalog or BotJobs."),
    ("Global", "sidecar online/offline", "Always", "Displays local backend health. Resolve offline status before doing work."),
    ("Home", "Shortcut cards", "Always", "Open the matching sidebar destination."),
    ("Import APIs", "Upload Files tab", "Always", "Shows file/folder upload workflow."),
    ("Import APIs", "Folder (Desktop) tab", "Always", "Shows local folder-path workflow."),
    ("Import APIs", "Drop area", "Upload tab", "Adds dropped .yaml, .yml, and .json files; subfolders are scanned."),
    ("Import APIs", "Browse Files", "Upload tab", "Opens a multi-file picker."),
    ("Import APIs", "Browse Folder", "Upload tab", "Opens a folder picker and adds supported files below it."),
    ("Import APIs", "Remove (x)", "After adding a file", "Removes one staged item before import."),
    ("Import APIs", "Import", "After files/path selected", "Imports specifications and reports specification, endpoint, and failure counts."),
    ("Import APIs", "Browse", "Desktop folder tab", "Selects one local folder."),
    ("API Catalog", "Search method / path", "Always", "Filters by method, path, or summary."),
    ("Test Cases", "New test case", "Disabled in 1.0.0", "Reserved; does not create a record in this release."),
    ("Bot Builder", "Suggestion buttons", "Empty conversation", "Sends the displayed prompt immediately."),
    ("Bot Builder", "Catalog action card", "After search action", "Expands/collapses endpoint evidence."),
    ("Bot Builder", "Open Designer", "After BotJob creation action", "Navigates to Designer; select the created job if it is not automatically highlighted."),
    ("Bot Builder", "View Results", "After execution action", "Navigates to Execute Tests."),
    ("Bot Builder", "Send", "When prompt is non-empty", "Sends the conversation; Enter also sends and Shift+Enter adds a line."),
    ("BotJob Designer", "+ New BotJob", "Always", "Prompts for a name and creates a saved BotJob shell."),
    ("BotJob Designer", "Saved BotJob row", "When jobs exist", "Loads the selected job and commands."),
    ("BotJob Designer", "Delete", "Job selected", "Deletes the BotJob after confirmation."),
    ("BotJob Designer", "Save", "Job selected", "Persists metadata, variables, order, configuration, and enabled state."),
    ("BotJob Designer", "+ Add variable", "Job selected", "Adds a variable row."),
    ("BotJob Designer", "secret checkbox", "Variable exists", "Causes Bash generation to require the value from the environment rather than embed an initial value."),
    ("BotJob Designer", "Variable delete (x)", "Variable exists", "Removes the variable from the working definition."),
    ("BotJob Designer", "Palette group heading", "Always", "Expands or collapses one command group."),
    ("BotJob Designer", "Palette command", "Job selected", "Adds the command to the end of the canvas and opens its editor."),
    ("BotJob Designer", "Drag grip", "Command exists", "Reorders the command in the workflow."),
    ("BotJob Designer", "Enabled checkbox", "Command exists", "Includes/excludes the command from execution; disabled API calls are excluded from Bash export."),
    ("BotJob Designer", "Expand/collapse", "Command exists", "Shows or hides command configuration."),
    ("BotJob Designer", "Command delete (x)", "Command exists", "Removes that command from the working definition."),
    ("Environments", "+ New Environment", "Always", "Opens the environment form."),
    ("Environments", "Star", "Non-default custom environment", "Sets the environment as default."),
    ("Environments", "Edit", "Custom environment", "Opens the existing environment in the form."),
    ("Environments", "Delete", "Custom environment", "Deletes after confirmation; built-in Mock cannot be deleted."),
    ("Environment form", "Close / Cancel", "Form open", "Discards unsaved edits."),
    ("Environment form", "Set as default", "Form open", "Makes the saved environment the default selection."),
    ("Environment form", "Save", "Name and Base URL present", "Validates header lines and persists the environment."),
    ("Scripts", "BotJob selector", "Always", "Selects the saved workflow used as the script source."),
    ("Scripts", "Environment selector", "Always", "Selects base URL and default headers."),
    ("Scripts", "Browse", "Desktop app", "Selects the exact output directory."),
    ("Scripts", "Create Bash Script", "Job, environment, and directory selected", "Writes a timestamped .sh file containing enabled API_CALL curl commands."),
    ("Execute Tests", "History / Hide History", "Always", "Shows or hides the saved-run list."),
    ("Execute Tests", "Environment selector", "Always", "Chooses the run target and script handoff environment."),
    ("Execute Tests", "BotJob selector", "Always", "Chooses the workflow; resets the displayed result."),
    ("Execute Tests", "Create Scripts", "BotJob selected", "Opens Scripts with job and environment query selections."),
    ("Execute Tests", "Run", "BotJob selected", "Creates a local run record and step audit."),
    ("Execute Tests", "Step row", "Result loaded", "Expands errors, assertions, request, and response when recorded."),
    ("Execution History", "All BotJobs filter", "History open", "Filters saved runs by BotJob."),
    ("Execution History", "Run row", "Runs exist", "Loads that run and closes History."),
    ("Mock Server", "Start / Stop", "Always", "Changes mock dashboard state."),
    ("Mock Server", "Clear", "Log contains rows", "Clears the in-app request/system log."),
    ("Reports", "Execution Run selector", "Runs exist", "Chooses the source run for HTML/CSV."),
    ("Reports", "HTML Download", "Run selected", "Downloads a human-readable run report."),
    ("Reports", "CSV Download", "Run selected", "Downloads step results for spreadsheet/BI use."),
    ("Reports", "Postman Download", "Always", "Downloads the whole catalog as Postman Collection v2.1 JSON."),
    ("Reports", "Bash/curl Download", "Always", "Downloads a simple whole-catalog Bash file; review its localhost base URL."),
    ("Settings", "Provider expand/collapse", "Always", "Shows or hides editable model/base URL/API-key fields."),
    ("Settings", "Save", "Provider expanded", "Persists the provider record; blank key preserves an existing key."),
    ("Settings", "Test", "Saved key exists", "Shows the current build's provider configuration test result."),
    ("Settings", "SET DEFAULT", "Saved key exists and provider is not default", "Makes the provider active for AI features."),
]

API_ROUTES = [
    ("GET", "/health", "Local backend liveness."),
    ("GET", "/catalog/endpoints", "List imported endpoints and mapping status."),
    ("POST", "/import", "Import a local folder from { folderPath }."),
    ("POST", "/import/upload", "Import uploaded OpenAPI/Swagger file content."),
    ("PUT", "/catalog/endpoints/{endpointId}/category", "Set or clear endpoint category mapping."),
    ("GET", "/taxonomy", "Return 25 banking categories and subcategories."),
    ("GET", "/agents", "List banking agents."),
    ("GET", "/agents/capabilities", "List agent capability counts."),
    ("POST", "/agents/ask", "Ask a banking agent."),
    ("POST", "/app-assistant/chat", "Send Bot Builder conversation messages."),
    ("GET", "/settings/ai-providers", "List provider settings without returning key values."),
    ("POST", "/settings/ai-providers", "Create or update a provider record."),
    ("POST", "/settings/ai-providers/set-default", "Set the default provider record."),
    ("POST", "/settings/ai-providers/test", "Return the current provider-test result."),
    ("GET", "/environments", "List environments."),
    ("POST", "/environments", "Create an environment."),
    ("PUT", "/environments/{id}", "Update an environment."),
    ("DELETE", "/environments/{id}", "Delete a non-built-in environment."),
    ("GET", "/botjobs", "List BotJobs."),
    ("POST", "/botjobs", "Create a BotJob shell."),
    ("GET", "/botjobs/{id}", "Get BotJob blocks, commands, and variables."),
    ("PUT", "/botjobs/{id}", "Save the complete BotJob definition."),
    ("DELETE", "/botjobs/{id}", "Delete a BotJob."),
    ("GET", "/botjobs/{id}/export/bash", "Generate BotJob-specific Bash; accepts environmentId query."),
    ("POST", "/botjobs/{id}/execute", "Create a run using { environmentId }."),
    ("GET", "/executions", "List runs; optional botJobId query filter."),
    ("GET", "/executions/{runId}/steps", "List step results for a run."),
    ("GET", "/executions/{runId}/report.html", "Download HTML run report."),
    ("GET", "/executions/{runId}/report.csv", "Download CSV run report."),
    ("GET", "/catalog/export/postman", "Download whole-catalog Postman JSON; optional baseUrl query."),
    ("GET", "/catalog/export/bash", "Download whole-catalog Bash; optional baseUrl query."),
    ("GET", "/mock/status", "Read mock dashboard state and port."),
    ("POST", "/mock/start", "Set mock state to running and add a system log row."),
    ("POST", "/mock/stop", "Set mock state to stopped and add a system log row."),
    ("GET", "/mock/log", "Read the mock log."),
    ("POST", "/mock/log/clear", "Clear the mock log."),
    ("GET", "/separation/progress", "Read packaged progress metadata when present."),
]

TROUBLESHOOTING = [
    ("sidecar offline", "Close and reopen ARAPI. Confirm no other process is occupying port 8787. If the status stays offline, contact the deployment administrator; the UI cannot work without the local backend."),
    ("Import is disabled", "Choose at least one supported file on Upload Files, or select a valid directory on Folder (Desktop). Supported extensions are .yaml, .yml, and .json."),
    ("Import reports zero endpoints", "Confirm the files contain OpenAPI/Swagger path operations, not only schemas/examples. Review the failure list and try one known-good specification."),
    ("Repeated catalog rows", "Avoid importing the same specification tree repeatedly when duplicate rows are observed. Record the source folder and contact support before cleaning shared client data."),
    ("Palette commands are dimmed", "Select or create a BotJob first."),
    ("Save does not enable", "For environments, Name and Base URL are mandatory. Header lines must use Key: Value. For scripts, job, environment, and desktop output directory are mandatory."),
    ("API call references a missing endpoint", "Open Designer, expand the API Call, select the current endpoint from the catalog, and Save. This can occur after catalog content is replaced."),
    ("Create Bash Script says there are no calls", "Enable at least one API_CALL and ensure it references an endpoint still present in the catalog."),
    ("bash is not recognized", "Install/use Git Bash, Windows Subsystem for Linux, or a CI agent with Bash and curl. Windows cmd.exe alone cannot interpret Bash syntax."),
    ("Script stops before the first curl", "A required variable guard failed. Set the named environment variable, including path parameters and sensitive headers, then run again."),
    ("Script ends with exit code 1", "One or more curl calls failed. Scroll to the first curl error, verify BASE_URL, network/TLS/authentication, and review the response body."),
    ("Run results are green but target evidence is absent", "Treat ARAPI's local run summary as an audit record, not independent proof of a downstream state change. Use the generated Bash script and target-side logs/data for acceptance."),
    ("Port 8855 cannot be reached", "The observed 1.0.0 C# desktop build maintains mock state/log in ARAPI. Do not assume an external listener is available unless your deployment administrator has enabled and verified one."),
    ("Reports has no run selector", "Execute a BotJob first. Catalog Postman/Bash exports remain available without a run."),
    ("AI provider Test shows success but AI calls fail", "The current desktop Test is a local configuration indicator. Verify endpoint, model, key entitlement, proxy/firewall, and an actual Bot Builder request."),
]

GLOSSARY = [
    ("API Catalog", "The imported endpoint inventory that constrains selectable API calls."),
    ("BotJob", "A named ordered workflow containing commands and variables."),
    ("Command", "One step in a BotJob, such as API_CALL or ASSERT_STATUS_CODE."),
    ("Environment", "A named base URL plus optional default headers."),
    ("Mapping", "Association between an endpoint and a banking business category."),
    ("Mock", "A local/synthetic test context intended to avoid a production banking backend."),
    ("Run", "One saved execution/audit record for a BotJob and environment."),
    ("Secret variable", "A BotJob variable that Bash export requires from the process environment."),
    ("Synthetic endpoint", "A mock-only catalog record that Bot Builder may create when no imported endpoint matches strongly enough."),
    ("Token", "A ${name} placeholder resolved from BotJob/runtime variables."),
]
